site_name: uSMS Documentation
site_url: https://www.usms.co.za
site_description: uSMS Online Documentation
site_author: uSMS Support Team

repo_url: https://github.com/inkeytech/docs
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - User Guide:
        - Sending your first SMS: user-guide/first-sms.md


copyright: Copyright &copy; 2021 <a href="https://www.usms.co.za">uSMS</a>, Maintained by the <a href="www.usms.co.za">uSMS Support Team</a>.

plugins:
    - search
